networks:
  agno_net:
    name: agno_net
    driver: bridge

volumes:
  agno_pgdata:

services:
  agno_postgres_database:
    image: ${DOCKER__POSTGRES__IMAGE:-pgvector/pgvector:pg17}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB__DATABASE_NAME:-postgres}
      POSTGRES_USER: ${DB__USER:-postgres}
      POSTGRES_PASSWORD: $DB__PASSWORD
    ports:
      - "${DB__PORT:-5432}:5432"
    volumes:
      - ${DB__VOLUME:-agno_pgdata}:/var/lib/postgresql/data
    networks:
      - agno_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB__DATABASE_NAME:-postgres} -p ${DB__PORT:-5432} -U ${DB__USER:-postgres}" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 15s

  # docker compose up app -d && docker compose attach app
  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    restart: unless-stopped
    working_dir: /app
    environment:
      DB__DATABASE_URI: "postgresql://${DB__USER:-postgres}:${DB__PASSWORD}@${DB__HOST:-agno_postgres_database}:${DB__PORT:-5432}/${DB__DATABASE_NAME:-postgres}"
    env_file:
      - path: .env
    stdin_open: true
    tty: true
    depends_on:
      agno_postgres_database:
        condition: service_healthy
    networks:
      - agno_net
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f 'python test.py' || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 3
    security_opt: [ "no-new-privileges:true" ]
